services:
  - type: web
    name: eventmaster
    env: docker
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true
      - key: APP_ENV
        value: production
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: eventmaster-db
          property: connectionString

databases:
  - name: eventmaster-db
    plan: free
    databaseName: eventmaster_db
    user: admin

version: "1"
